### ISSUE TITLE
Error Starting The App

### ISSUE THREAD

**Issue by Stoutscientist** [hishizuka/pizero_bikecomputer#13]
After following the guide to install this, and running it, I run into this error:

` ########## INITIALIZE START ##########

Traceback (most recent call last):
  File "/home/pi/pizero_bikecomputer/pizero_bikecomputer.py", line 78, in <module>
    main()
  File "/home/pi/pizero_bikecomputer/pizero_bikecomputer.py", line 23, in main
    config = config.Config()
  File "/home/pi/pizero_bikecomputer/modules/config.py", line 688, in __init__
    shutil.copy(self.G_INSTALL_PATH+"layouts/"+"layout-cycling.yaml", self.G_LAYOUT_FILE)
  File "/usr/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/pizero_bikecomputer/layouts/layout-cycling.yaml'
`

I'm running Pi OS 64 Bit (Full) on my Pi 02w using the Pi user

**Comment by Stoutscientist** [comment]
> @Stoutscientist Sorry for the late reply.
> 
> The first error is due to your incorrect specification of G_INSTALL_PATH (maybe /root/pizero_bikecomputer), so I will not follow up.
> 
> The second error depends on which LCD module you are using and whether you are starting with X Window / Console. This is also described in the [software_installation](https://github.com/hishizuka/pizero_bikecomputer/blob/master/doc/software_installation.md#quick-start) and you can run it.
> 
> Perhaps you run the following in a console `$ python3 pizero_bikecomputer.py` and it will not start.

Ohhh that makes sense! Thank you!
